### PR TITLE
Remove unnecessary logic based on orientation to really fix #2

### LINKED ISSUE #2: Orientation aware
I had to disable this bit to actually get correct width / height
```
  // Sets screen width and height
    // if (orientation == Orientation.portrait) {
    width = boxConstraints.maxWidth;
    height = boxConstraints.maxHeight;
    // } else {
    //   width = boxConstraints.maxHeight;
    //   height = boxConstraints.maxWidth;
    // }
```

AS far as I know then LayoutBuilder is orientation aware...ie width is always width and you should not artificially change it.

### PR DESCRIPTION
**Pull request by radvansky-tomas**
I don't really know what last update should fix, but it did not help on my device. So I am sharing my fix. 
As I already explained in issue #2 flutter layout listener should be aware of orientation and width & height should be set. You dont need any extra logic there

### CODE REVIEW

**Comment by CoderUni** [comment]
Thanks for the PR but this won't make the sizes (`.h`, `.w`, `.sp`) stay the same when changing from `portrait` to `landscape` orientation. You could reproduce this by setting a `Container's` width and height using `.w` and `.h` and then rotate your phone to go landscape mode.

**Comment by radvansky-tomas** [comment]
.h and .w should not stay the same...thats the whole point of this PR...they should come from actual orientation.

With .sp I agree, its bad implementation to get .sp from width only...it should be ration of width AND height. Will do some fix about it.

And just tested your example, which works correctly with this PR:

12.5% Height and 50 % width

With current code it would use 50% height and 12.5% width in landscape! 

IMG_2038 2

IMG_2039

**Comment by CoderUni** [comment]
Thanks for helping me improve this package. I also agree that the `.sp` implementation could be improved. I'm sorry I couldn't merge your PR because there are many instances where `.h` and `.w` shouldn't come from the actual orientation. An example would be with images, we don't want the image's height and width to change drastically when changing orientation like what happened to the container above. If you want to use your version of `responsive_sizer`, feel free to fork my package and create a new one. This video helped me publish my first package: https://www.youtube.com/watch?v=6OqXMPbDCik

**Comment by radvansky-tomas** [comment]
Sure np I can release it separately. But that make no sense...

If you want to have image (logo) for example present on top of your screen with width = 80% and height = 20%

And you move it to landscape...with your code you will have 20% width and 80 % height.... ie when in first situation user could see 80% of content (form for example) not he will see 20%...

Actual viewport and available space, thats all what matters. Anyway will continue my journey elsewhere/// 

Wish you all the best then

**Comment by CoderUni** [comment]
I get what you're trying to do with the widget having the actual width and height  during landscape mode but I wanted to be able to make the container have the same dimensions regardless of the orientation. I wish you the best with your separate package.

**Pull request closed without merging**
